spring:
  application:
    name: aec-event
  datasource:
    url:      ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/aec}
    username: ${DATASOURCE_USER:aec}
    password: ${DATASOURCE_PASS:2412}
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}

server:
  port: ${SERVER_PORT:8087}

jwt:
  secret:    ${JWT_SECRET:Cuetm0BgR8Bjk8Mo2OXtOlOxkc/N1K2g3vKx82o8Lcw=}
  accessMs:  ${JWT_ACCESS_MS:3600000}
  refreshMs: ${JWT_REFRESH_MS:86400000}
